# Generated by Django 5.2.3 on 2025-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=150)),
                ("title", models.TextField(max_length=150)),
                ("description", models.TextField(max_length=900)),
                ("content", models.TextField(max_length=900000)),
            ],
        ),
    ]
